// This file is generated by scripts/sync-flux-version.mjs
// Do not edit by hand.

export const fluxVersion = "0.1.7";
export const fluxRepoUrl = "https://github.com/cbassuarez/flux";
export const fluxRepoPermalink = "https://github.com/cbassuarez/flux/tree/v0.1.7";
